import Head from 'next/head';
import Table from '../Components/MainContent/Table';
import Header from '../Components/Header/Header';
import SideBar from '../Components/SideBar/SideBar';
import styled from 'styled-components';

export default function Home() {
   return (
      <AppWrapper>
         <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>

         <MainContainer>
            {/* <TempBox>asdasd</TempBox> */}
            <Header />
            <ContainerTableSideBar>
               <SideBar />
               <Table />
            </ContainerTableSideBar>
         </MainContainer>
      </AppWrapper>
   );
}
const AppWrapper = styled.div`
   display: flex;
   min-height: 100vh;
`;
const MainContainer = styled.main`
   width: 100%;
   height: 100%;
   /* border: solid 5px #b38f8f;
   background-color: '#c02b2b'; */
`;
const TempBox = styled.div`
   width: 1000px;
   height: 1000px;
   border: solid 5px #3f3e3e;
   background-color: '#c02b2b';
`;

const ContainerTableSideBar = styled.div`
   display: flex;
   height: 100%;
`;
